version: 0.0
os: linux
files:
  - source: /codebuild/output/src2399667400/src/dist
    destination: /var/www/html/
permissions:
  - object: /var/www/html/
    pattern: "**"
    owner: apache
    group: apache

