version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Post-build phase"

artifacts:
  files:
    - dist/**/*
