version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase"
      - npm cache clean --force
      - npm install -g update-node
      - npm i -g npm-upgrade
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Post-build phase"

artifacts:
  files:
    - dist/**/*
