version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Pre-build phase"
      - npm install
      - npm install @vue/cli-service --save-dev
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Post-build phase"

artifacts:
  files:
    - dist/**/*
