version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Pre-build phase"
      - npm install
      - npm install -g @vue/cli
  build:
    commands:
    - npm run build
  post_build:
    commands:
      - pwd
      - echo "Post-build phase"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
