version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Pre-build phase"
      - npm install axios
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Post-build phase"

artifacts:
  files:
    - dist/**/*
