version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      - npm install -g @vue/cli
      - npm install bootstrap-vue bootstrap
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
    - 'appspec.yml'

