version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Pre-build phase"
  build:
    commands:
    - npm install
    - npm install -g @vue/cli
    - npm run build
  post_build:
    commands:
      - echo "Post-build phase"

artifacts:
  files:
    - dist/**/*
