version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @vue/cli
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
    - 'appspec.yml'
  base-directory: 'dist'

